"""
Untitled Project - Generated by PyDesigner
https://pydesigner.qzz.io

This code uses PyQt5. To use PySide6 instead, replace:
  from PyQt5.QtWidgets import ... -> from PySide6.QtWidgets import ...
  from PyQt5.QtCore import ... -> from PySide6.QtCore import ...
  from PyQt5.QtGui import ... -> from PySide6.QtGui import ...
  app.exec_() -> app.exec()

Required libraries:
pip install PyQt5
"""
from functools import partial
import sys

from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QWidget, QPushButton, QLabel,
    QLineEdit, QFrame, QCheckBox, QRadioButton, QComboBox,
    QTextEdit, QButtonGroup, QListWidget, QGraphicsView, QGraphicsScene
)
from PyQt5.QtCore import Qt, QByteArray, QPoint, QSize
from PyQt5.QtGui import QFont, QIcon, QPixmap, QImage, QCursor, QColor
from ColorCircle import ColorCircle, ColorCircleDialog
class App(QMainWindow):
    

    
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Untitled Project")
        #self.setGeometry(0, 0, 800, 600)
        
        geometry = app.desktop().availableGeometry()
      #  geometry.setHeight(geometry.height() - (titleBarHeight*2))
        self.setGeometry(geometry)
        
        
        
        # Central widget
        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)
       
        # Create widgets
        self._create_widgets()
        
        
        
        
    def _create_widgets(self):
        """Create and place all widgets"""
        
        # button_1
        
        
        self.BImport = QPushButton("Import", self.central_widget)
        self.BImport.setGeometry(660, 40, 120, 36)
        self.BImport.setFont(QFont("Arial", 12))
        self.BImport.setStyleSheet("background-color: #3b82f6; color: #ffffff;")
        self.BImport.clicked.connect(self.Import)
        
        # entry_1  
        self.img_input = QLineEdit(self.central_widget)
        self.img_input.setGeometry(10, 40, 130, 40)
        self.img_input.setPlaceholderText("Enter text...")
        self.img_input.setFont(QFont("Arial", 12))
        
        # textarea_1
        self.label_1 = QLabel("Enter filename of Image and hit Import", self.central_widget)
        self.label_1.setGeometry(200, 40, 400, 80)
        self.label_1.setFont(QFont("Arial", 12))
        self.label_1.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_1.setStyleSheet("background-color: #ffffff; color: #000000;")
        self.label_1.setWordWrap(True)
        
        self.label_2 = QLabel("Show Sample", self.central_widget)
        self.label_2.setGeometry(800, 500, 400, 80)
        self.label_2.setFont(QFont("Arial", 12))
        self.label_2.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_2.setStyleSheet("background-color: #ffffff; color: #000000;")
        self.label_2.setWordWrap(True)
        
        self.label_3 = QLabel("Show Wheel", self.central_widget)
        self.label_3.setGeometry(800, 1500, 400, 80)
        self.label_3.setFont(QFont("Arial", 12))
        self.label_3.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_3.setStyleSheet("background-color: #ffffff; color: #000000;")
        self.label_3.setWordWrap(True)
        
        self.label_4 = QLabel("Show Difference", self.central_widget)
        self.label_4.setGeometry(1500, 1500, 400, 80)
        self.label_4.setFont(QFont("Arial", 12))
        self.label_4.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_4.setStyleSheet("background-color: #ffffff; color: #000000;")
        self.label_4.setWordWrap(True)
        
        self.label_5 = QLabel("Show Color", self.central_widget)
        self.label_5.setGeometry(1500, 1100, 400, 80)
        self.label_5.setFont(QFont("Arial", 12))
        self.label_5.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_5.setStyleSheet("background-color: #ffffff; color: #000000;")
        self.label_5.setWordWrap(True)       
        
       
        
    # ==========================================
    # Event Handlers - Implement your logic here
    # ==========================================
        self.C=QCursor()
        self.diff=(0,0,0)
        self.img = QLabel(self)
        #(x,y,w,h)
        self.img.setGeometry(200, 500, 400, 1200)
        self.ccd=ColorCircleDialog(self, self.central_widget)
        self.ccd.setGeometry(800,800,self.ccd.width(),self.ccd.height())
        self.cc=self.ccd.wid
      #  self.cc.x=800
        #self.cc.y=800
        
        
   

    def Hcolor(self,imgc):
        rgb=imgc.getRgb()
        hr="{:02x}".format((rgb[0]))
        hg="{:02x}".format((rgb[1]))
        hb="{:02x}".format((rgb[2]))
        return "#"+''.join([hr,hg,hb])
        
    def BB(self,pos,x,y,w,h):
        if(pos.x()>=x and pos.x()<=w and pos.y()>=y and pos.y()<=h):
            return True
        return False
        
    
    def mousePressEvent(self, m):
        p=self.C.pos()
        shiftedp=p-( QPoint(self.img.x(),self.img.y()))
        wheelp=p-(QPoint(self.ccd.x(),self.ccd.y()))

        if m.button() == Qt.LeftButton:
            # handle the left-button press in here
        
            self.imgc=self.i.pixelColor(shiftedp)
            hcolor=self.Hcolor(self.imgc)
            self.label_1.setText(f"color {self.imgc.getRgb()}  global x: {p.x()} img x: {shiftedp.x()} global y: {p.y()} img y : {shiftedp.y()}")
            print(f"color {self.imgc.getRgb()}  global x: {p.x()} img x: {shiftedp.x()} global y: {p.y()} img y : {shiftedp.y()}")
            self.label_2.setStyleSheet(f"background-color: {hcolor}; color: #000000;")
            self.label_2.setText(f"{self.imgc.getRgb()}")
            print(hcolor)
            
            
            
            irgb=self.imgc.getRgb()
            self.label_4.setText(f"{self.diff}")
            newc=QColor()
            newdiff=(irgb[0] - self.diff[0]),(irgb[1] - self.diff[1]),(irgb[2] - self.diff[2])
            match [newdiff[0]<0, newdiff[0]>255]:
                case [False,True]:
                    d0=255
                case [True,False]:
                    d0=0
                case _:
                    d0=newdiff[0]
            match [newdiff[1]<0, newdiff[1]>255]:
                case [False,True]:
                    d1=255
                case [True,False]:
                    d1=0
                case _:
                    d1=newdiff[1]
            match [newdiff[2]<0, newdiff[2]>255]:
                case [False,True]:
                    d2=255
                case [True,False]:
                    d2=0
                case _:
                    d2=newdiff[2]                
            fixeddiff=(d0,d1,d2)
            
            newc=newc.fromRgb(fixeddiff[0],fixeddiff[1],fixeddiff[2])
        
            if(newc.value()<0.5):
                tcolor="#ffffff"
            else:
                tcolor="#000000"
            self.label_5.setText(f"{newc.getRgb()}")  
            self.label_5.setStyleSheet(f"background-color: {self.Hcolor(newc)}; color: {tcolor};")
               
        else:
            self.label_1.setText("out of bounds")
            print("out of bounds")
            
       

            
    def Import(self):
        """
        Handle HW event
        TODO: Implement your logic here
        """
        
        self.pixmap = QPixmap(self.img_input.text())
        w=self.img.width()
        h=self.img.height()
        s=QSize(w,h)
        self.pixmap=self.pixmap.scaled(s)
        self.img.setPixmap(self.pixmap)
        self.img.setScaledContents(True)
        #ww=self.img.width
        #self.setCentralWidget(label)
        self.i=self.pixmap.toImage()

        
        
        
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = App()
    window.show()
    a=0xffffff
    b=0x3b82f6
    print(a-b)
    
    
    sys.exit(app.exec_())
